# These are supported funding model platforms

github: [vgrem]
# open_collective: # add once the collective is live
ko_fi: vgrem
# patreon: # not used
# tidelift: # not used
# ko_fi: # not used
# community_bridge: # not used
# liberapay: # not used
# issuehunt: # not used
# lfx_crowdfunding: # not used
# polar: # not used
# buy_me_a_coffee: # not used
custom: https://paypal.me/ossvgrem # one-off donation
