from enum import Enum


class SynchronizationSecret(Enum):
    None_ = "0"
    UserName = "1"
    Password = "2"
    SecretToken = "3"
    AppKey = "4"
    BaseAddress = "5"
    ClientIdentifier = "6"
    ClientSecret = "7"
    SingleSignOnType = "11"
    Sandbox = "12"
    Url = "13"
    Domain = "14"
    ConsumerKey = "15"
    ConsumerSecret = "16"
    TokenKey = "17"
    TokenExpiration = "18"
    Oauth2AccessToken = "19"
    Oauth2AccessTokenCreationTime = "20"
    Oauth2RefreshToken = "21"
    SyncAll = "22"
    InstanceName = "24"
    Oauth2ClientId = "27"
    Oauth2ClientSecret = "28"
    CompanyId = "29"
    UpdateKeyOnSoftDelete = "30"
    SynchronizationSchedule = "33"
    SystemOfRecord = "34"
    SandboxName = "35"
    EnforceDomain = "36"
    SyncNotificationSettings = "37"
    SkipOutOfScopeDeletions = "40"
    Oauth2AuthorizationCode = "62"
    Oauth2RedirectUri = "63"
    ApplicationTemplateIdentifier = "64"
    Oauth2TokenExchangeUri = "65"
    Oauth2AuthorizationUri = "66"
    AuthenticationType = "67"
    Server = "70"
    PerformInboundEntitlementGrants = "100"
    HardDeletesEnabled = "101"
    SyncAgentCompatibilityKey = "102"
    SyncAgentADContainer = "103"
    ValidateDomain = "206"
    TestReferences = "207"
    ConnectionString = "250"

    @property
    def entity_type_name(self):
        return "microsoft.graph.SynchronizationSecret"
