from __future__ import annotations

from dataclasses import dataclass

from office365.runtime.client_value import ClientValue


@dataclass
class ChangeNotificationEncryptedContent(ClientValue):
    """Represents the encrypted data attached to a change notification.

    Args:
        data (str): Base64-encoded encrypted data that produces a full resource represented as JSON. The data has been encrypted with the provided dataKey using an AES/CBC/PKCS5PADDING cipher suite.
        data_key (str): ase64-encoded symmetric key generated by Microsoft Graph to encrypt the data value and to generate the data signature. This key is encrypted with the certificate public key that was provided during the subscription. It must be decrypted with the certificate private key before it can be used to decrypt the data or verify the signature. This key has been encrypted with the following cipher suite: RSA/ECB/OAEPWithSHA1AndMGF1Padding.
        data_signature (str): Base64-encoded HMAC-SHA256 hash of the data for validation purposes.
        encryption_certificate_id (str): ID of the certificate used to encrypt the dataKey.
        encryption_certificate_thumbprint (str): Hexadecimal representation of the thumbprint of the certificate used to encrypt the dataKey
    """

    data: str | None = None
    dataKey: str | None = None
    dataSignature: str | None = None
    encryptionCertificateId: str | None = None
    encryptionCertificateThumbprint: str | None = None
