from enum import Enum


class ScheduleEntityTheme(Enum):
    white = "0"
    blue = "1"
    green = "2"
    purple = "3"
    pink = "4"
    yellow = "5"
    gray = "6"
    darkBlue = "7"
    darkGreen = "8"
    darkPurple = "9"
    darkPink = "10"
    darkYellow = "11"
    unknownFutureValue = "12"
    darkRed = "13"
    cranberry = "14"
    darkOrange = "15"
    bronze = "16"
    peach = "17"
    gold = "18"
    lime = "19"
    forest = "20"
    lightGreen = "21"
    jade = "22"
    lightTeal = "23"
    darkTeal = "24"
    steel = "25"
    skyBlue = "26"
    blueGray = "27"
    lavender = "28"
    lilac = "29"
    plum = "30"
    magenta = "31"
    darkBrown = "32"
    beige = "33"
    charcoal = "34"
    silver = "35"

    @property
    def entity_type_name(self):
        return "microsoft.graph.ScheduleEntityTheme"
