from enum import Enum


class CloudPcOnPremisesConnectionHealthCheckErrorType(Enum):
    dnsCheckFqdnNotFound = "100"
    dnsCheckNameWithInvalidCharacter = "101"
    dnsCheckUnknownError = "199"
    adJoinCheckFqdnNotFound = "200"
    adJoinCheckIncorrectCredentials = "201"
    adJoinCheckOrganizationalUnitNotFound = "202"
    adJoinCheckOrganizationalUnitIncorrectFormat = "203"
    adJoinCheckComputerObjectAlreadyExists = "204"
    adJoinCheckAccessDenied = "205"
    adJoinCheckCredentialsExpired = "206"
    adJoinCheckAccountLockedOrDisabled = "207"
    adJoinCheckAccountQuotaExceeded = "208"
    adJoinCheckServerNotOperational = "209"
    adJoinCheckUnknownError = "299"
    endpointConnectivityCheckCloudPcUrlNotAllowListed = "300"
    endpointConnectivityCheckWVDUrlNotAllowListed = "301"
    endpointConnectivityCheckIntuneUrlNotAllowListed = "302"
    endpointConnectivityCheckAzureADUrlNotAllowListed = "303"
    endpointConnectivityCheckLocaleUrlNotAllowListed = "304"
    endpointConnectivityCheckUnknownError = "399"
    azureAdDeviceSyncCheckDeviceNotFound = "400"
    azureAdDeviceSyncCheckLongSyncCircle = "401"
    azureAdDeviceSyncCheckConnectDisabled = "402"
    azureAdDeviceSyncCheckDurationExceeded = "403"
    azureAdDeviceSyncCheckScpNotConfigured = "404"
    azureAdDeviceSyncCheckTransientServiceError = "498"
    azureAdDeviceSyncCheckUnknownError = "499"
    resourceAvailabilityCheckNoSubnetIP = "500"
    resourceAvailabilityCheckSubscriptionDisabled = "501"
    resourceAvailabilityCheckAzurePolicyViolation = "502"
    resourceAvailabilityCheckSubscriptionNotFound = "503"
    resourceAvailabilityCheckSubscriptionTransferred = "504"
    resourceAvailabilityCheckGeneralSubscriptionError = "505"
    resourceAvailabilityCheckUnsupportedVNetRegion = "506"
    resourceAvailabilityCheckResourceGroupInvalid = "507"
    resourceAvailabilityCheckVNetInvalid = "508"
    resourceAvailabilityCheckSubnetInvalid = "509"
    resourceAvailabilityCheckResourceGroupBeingDeleted = "510"
    resourceAvailabilityCheckVNetBeingMoved = "511"
    resourceAvailabilityCheckSubnetDelegationFailed = "512"
    resourceAvailabilityCheckSubnetWithExternalResources = "513"
    resourceAvailabilityCheckResourceGroupLockedForReadonly = "514"
    resourceAvailabilityCheckResourceGroupLockedForDelete = "515"
    resourceAvailabilityCheckNoIntuneReaderRoleError = "516"
    resourceAvailabilityCheckIntuneDefaultWindowsRestrictionViolation = "517"
    resourceAvailabilityCheckIntuneCustomWindowsRestrictionViolation = "518"
    resourceAvailabilityCheckDeploymentQuotaLimitReached = "519"
    resourceAvailabilityCheckTransientServiceError = "598"
    resourceAvailabilityCheckUnknownError = "599"
    permissionCheckNoSubscriptionReaderRole = "600"
    permissionCheckNoResourceGroupOwnerRole = "601"
    permissionCheckNoVNetContributorRole = "602"
    permissionCheckNoResourceGroupNetworkContributorRole = "603"
    permissionCheckNoWindows365NetworkUserRole = "604"
    permissionCheckNoWindows365NetworkInterfaceContributorRole = "605"
    permissionCheckTransientServiceError = "698"
    permissionCheckUnknownError = "699"
    udpConnectivityCheckStunUrlNotAllowListed = "800"
    udpConnectivityCheckTurnUrlNotAllowListed = "801"
    udpConnectivityCheckUrlsNotAllowListed = "802"
    udpConnectivityCheckUnknownError = "899"
    internalServerErrorDeploymentCanceled = "900"
    internalServerErrorAllocateResourceFailed = "901"
    internalServerErrorVMDeploymentTimeout = "902"
    internalServerErrorUnableToRunDscScript = "903"
    ssoCheckKerberosConfigurationError = "904"
    internalServerUnknownError = "999"
    unknownFutureValue = "1000"

    none = "-1"

    @property
    def entity_type_name(self):
        return "microsoft.graph.CloudPcOnPremisesConnectionHealthCheckErrorType"
