from __future__ import annotations

from enum import Enum


class Label(Enum):
    title = "0"
    url = "1"
    createdBy = "2"
    lastModifiedBy = "3"
    authors = "4"
    createdDateTime = "5"
    lastModifiedDateTime = "6"
    fileName = "7"
    fileExtension = "8"
    unknownFutureValue = "12"
    containerName = "13"
    containerUrl = "14"
    iconUrl = "15"
    assignedToPeople = "16"
    closedBy = "17"
    closedDate = "18"
    priority = "19"
    sprintName = "20"
    tags = "21"
    severity = "22"
    state = "23"
    dueDate = "24"
    itemParentId = "25"
    itemPath = "26"
    itemType = "27"
    numberOfReactions = "28"
    parentUrl = "29"
    priorityNormalized = "30"
    reportedBy = "31"
    secondaryId = "32"
    personEmails = "33"
    personAddresses = "34"
    personAnniversaries = "35"
    personName = "36"
    personNote = "37"
    personPhones = "38"
    personCurrentPosition = "39"
    personWebAccounts = "40"
    personWebSite = "41"
    personSkills = "42"
    personProjects = "43"
    personAccount = "44"
    personAwards = "45"
    personCertifications = "46"
    personAssistants = "47"
    personColleagues = "48"
    personManager = "49"
    personAlternateContacts = "50"
    personEmergencyContacts = "51"
    personEducationalActivities = "52"
    personInterests = "53"
    personLanguages = "54"
    personPublications = "55"
    personPatents = "56"
    personWorkPositions = "57"

    @property
    def entity_type_name(self) -> str:
        return "microsoft.graph.externalConnectors.Label"
