from enum import Enum


class PrintFinishing(Enum):
    none = "3"
    staple = "4"
    punch = "5"
    cover = "6"
    bind = "7"
    saddleStitch = "8"
    stitchEdge = "9"
    stapleTopLeft = "20"
    stapleBottomLeft = "21"
    stapleTopRight = "22"
    stapleBottomRight = "23"
    stitchLeftEdge = "24"
    stitchTopEdge = "25"
    stitchRightEdge = "26"
    stitchBottomEdge = "27"
    stapleDualLeft = "28"
    stapleDualTop = "29"
    stapleDualRight = "30"
    stapleDualBottom = "31"
    unknownFutureValue = "32"
    stapleTripleLeft = "33"
    stapleTripleTop = "34"
    stapleTripleRight = "35"
    stapleTripleBottom = "36"
    bindLeft = "37"
    bindTop = "38"
    bindRight = "39"
    bindBottom = "40"
    foldAccordion = "41"
    foldDoubleGate = "42"
    foldGate = "43"
    foldHalf = "44"
    foldHalfZ = "45"
    foldLeftGate = "46"
    foldLetter = "47"
    foldParallel = "48"
    foldPoster = "49"
    foldRightGate = "50"
    foldZ = "51"
    foldEngineeringZ = "52"
    punchTopLeft = "53"
    punchBottomLeft = "54"
    punchTopRight = "55"
    punchBottomRight = "56"
    punchDualLeft = "57"
    punchDualTop = "58"
    punchDualRight = "59"
    punchDualBottom = "60"
    punchTripleLeft = "61"
    punchTripleTop = "62"
    punchTripleRight = "63"
    punchTripleBottom = "64"
    punchQuadLeft = "65"
    punchQuadTop = "66"
    punchQuadRight = "67"
    punchQuadBottom = "68"
    fold = "69"
    trim = "70"
    bale = "71"
    bookletMaker = "72"
    coat = "73"
    laminate = "74"
    trimAfterPages = "75"
    trimAfterDocuments = "76"
    trimAfterCopies = "77"
    trimAfterJob = "78"

    @property
    def entity_type_name(self):
        return "microsoft.graph.PrintFinishing"
