from office365.runtime.client_value import ClientValue


class RenderListDataOverrideParameters(ClientValue):

    def __init__(
        self,
        casc_del_warn_message: str = None,
        custom_action: str = None,
        drill_down: str = None,
        field: str = None,
        field_internal_name: str = None,
        filter_: str = None,
        filter_data: str = None,
        filter_data1: str = None,
        filter_data10: str = None,
        filter_data2: str = None,
        filter_data3: str = None,
        filter_data4: str = None,
        filter_data5: str = None,
        filter_data6: str = None,
        filter_data7: str = None,
        filter_data8: str = None,
        filter_data9: str = None,
        filter_field: str = None,
        filter_field1: str = None,
        filter_field10: str = None,
        filter_field2: str = None,
        filter_field3: str = None,
        filter_field4: str = None,
        filter_field5: str = None,
        filter_field6: str = None,
        filter_field7: str = None,
        filter_field8: str = None,
        filter_field9: str = None,
        filter_fields: str = None,
        filter_fields1: str = None,
        filter_fields10: str = None,
        filter_fields2: str = None,
        filter_fields3: str = None,
        filter_fields4: str = None,
        filter_fields5: str = None,
        filter_fields6: str = None,
        filter_fields7: str = None,
        filter_fields8: str = None,
        filter_fields9: str = None,
        filter_lookup_id: str = None,
        filter_lookup_id1: str = None,
        filter_lookup_id10: str = None,
        filter_lookup_id2: str = None,
        filter_lookup_id3: str = None,
        filter_lookup_id4: str = None,
        filter_lookup_id5: str = None,
        filter_lookup_id6: str = None,
        filter_lookup_id7: str = None,
        filter_lookup_id8: str = None,
        filter_lookup_id9: str = None,
        filter_op: str = None,
        filter_op1: str = None,
        filter_op10: str = None,
        filter_op2: str = None,
        filter_op3: str = None,
        filter_op4: str = None,
        filter_op5: str = None,
        filter_op6: str = None,
        filter_op7: str = None,
        filter_op8: str = None,
        filter_op9: str = None,
        filter_value: str = None,
        filter_value1: str = None,
        filter_value10: str = None,
        filter_value2: str = None,
        filter_value3: str = None,
        filter_value4: str = None,
        filter_value5: str = None,
        filter_value6: str = None,
        filter_value7: str = None,
        filter_value8: str = None,
        filter_value9: str = None,
        filter_values: str = None,
        filter_values1: str = None,
        filter_values10: str = None,
        filter_values2: str = None,
        filter_values3: str = None,
        filter_values4: str = None,
        filter_values5: str = None,
        filter_values6: str = None,
        filter_values7: str = None,
        filter_values8: str = None,
        filter_values9: str = None,
        group_string: str = None,
        has_override_select_command: str = None,
        id_: str = None,
        inplace_full_list_search: str = None,
        inplace_search_query: str = None,
        is_csr: str = None,
        is_group_render: str = None,
        is_xsl_view: str = None,
        list_view_page_url: str = None,
        override_row_limit: str = None,
        override_scope: str = None,
        override_select_command: str = None,
        page_first_row: str = None,
        page_last_row: str = None,
        query_params: dict = None,
        root_folder: str = None,
        root_folder_unique_id: str = None,
        sort_dir: str = None,
        sort_dir1: str = None,
        sort_dir10: str = None,
        sort_dir2: str = None,
        sort_dir3: str = None,
        sort_dir4: str = None,
        sort_dir5: str = None,
        sort_dir6: str = None,
        sort_dir7: str = None,
        sort_dir8: str = None,
        sort_dir9: str = None,
        sort_field: str = None,
        sort_field1: str = None,
        sort_field10: str = None,
        sort_field2: str = None,
        sort_field3: str = None,
        sort_field4: str = None,
        sort_field5: str = None,
        sort_field6: str = None,
        sort_field7: str = None,
        sort_field8: str = None,
        sort_field9: str = None,
        sort_fields: str = None,
        sort_field_values: str = None,
        view: str = None,
        view_count: str = None,
        view_id: str = None,
        view_path: str = None,
        web_part_id: str = None,
    ):
        super(RenderListDataOverrideParameters, self).__init__()
        self.CascDelWarnMessage = casc_del_warn_message
        self.CustomAction = custom_action
        self.DrillDown = drill_down
        self.Field = field
        self.FieldInternalName = field_internal_name
        self.Filter = filter_
        self.FilterData = filter_data
        self.FilterData1 = filter_data1
        self.FilterData10 = filter_data10
        self.FilterData2 = filter_data2
        self.FilterData3 = filter_data3
        self.FilterData4 = filter_data4
        self.FilterData5 = filter_data5
        self.FilterData6 = filter_data6
        self.FilterData7 = filter_data7
        self.FilterData8 = filter_data8
        self.FilterData9 = filter_data9
        self.FilterField = filter_field
        self.FilterField1 = filter_field1
        self.FilterField10 = filter_field10
        self.FilterField2 = filter_field2
        self.FilterField3 = filter_field3
        self.FilterField4 = filter_field4
        self.FilterField5 = filter_field5
        self.FilterField6 = filter_field6
        self.FilterField7 = filter_field7
        self.FilterField8 = filter_field8
        self.FilterField9 = filter_field9
        self.FilterFields = filter_fields
        self.FilterFields1 = filter_fields1
        self.FilterFields10 = filter_fields10
        self.FilterFields2 = filter_fields2
        self.FilterFields3 = filter_fields3
        self.FilterFields4 = filter_fields4
        self.FilterFields5 = filter_fields5
        self.FilterFields6 = filter_fields6
        self.FilterFields7 = filter_fields7
        self.FilterFields8 = filter_fields8
        self.FilterFields9 = filter_fields9
        self.FilterLookupId = filter_lookup_id
        self.FilterLookupId1 = filter_lookup_id1
        self.FilterLookupId10 = filter_lookup_id10
        self.FilterLookupId2 = filter_lookup_id2
        self.FilterLookupId3 = filter_lookup_id3
        self.FilterLookupId4 = filter_lookup_id4
        self.FilterLookupId5 = filter_lookup_id5
        self.FilterLookupId6 = filter_lookup_id6
        self.FilterLookupId7 = filter_lookup_id7
        self.FilterLookupId8 = filter_lookup_id8
        self.FilterLookupId9 = filter_lookup_id9
        self.FilterOp = filter_op
        self.FilterOp1 = filter_op1
        self.FilterOp10 = filter_op10
        self.FilterOp2 = filter_op2
        self.FilterOp3 = filter_op3
        self.FilterOp4 = filter_op4
        self.FilterOp5 = filter_op5
        self.FilterOp6 = filter_op6
        self.FilterOp7 = filter_op7
        self.FilterOp8 = filter_op8
        self.FilterOp9 = filter_op9
        self.FilterValue = filter_value
        self.FilterValue1 = filter_value1
        self.FilterValue10 = filter_value10
        self.FilterValue2 = filter_value2
        self.FilterValue3 = filter_value3
        self.FilterValue4 = filter_value4
        self.FilterValue5 = filter_value5
        self.FilterValue6 = filter_value6
        self.FilterValue7 = filter_value7
        self.FilterValue8 = filter_value8
        self.FilterValue9 = filter_value9
        self.FilterValues = filter_values
        self.FilterValues1 = filter_values1
        self.FilterValues10 = filter_values10
        self.FilterValues2 = filter_values2
        self.FilterValues3 = filter_values3
        self.FilterValues4 = filter_values4
        self.FilterValues5 = filter_values5
        self.FilterValues6 = filter_values6
        self.FilterValues7 = filter_values7
        self.FilterValues8 = filter_values8
        self.FilterValues9 = filter_values9
        self.GroupString = group_string
        self.HasOverrideSelectCommand = has_override_select_command
        self.ID = id_
        self.InplaceFullListSearch = inplace_full_list_search
        self.InplaceSearchQuery = inplace_search_query
        self.IsCSR = is_csr
        self.IsGroupRender = is_group_render
        self.IsXslView = is_xsl_view
        self.ListViewPageUrl = list_view_page_url
        self.OverrideRowLimit = override_row_limit
        self.OverrideScope = override_scope
        self.OverrideSelectCommand = override_select_command
        self.PageFirstRow = page_first_row
        self.PageLastRow = page_last_row
        self.QueryParams = query_params
        self.RootFolder = root_folder
        self.RootFolderUniqueId = root_folder_unique_id
        self.SortDir = sort_dir
        self.SortDir1 = sort_dir1
        self.SortDir10 = sort_dir10
        self.SortDir2 = sort_dir2
        self.SortDir3 = sort_dir3
        self.SortDir4 = sort_dir4
        self.SortDir5 = sort_dir5
        self.SortDir6 = sort_dir6
        self.SortDir7 = sort_dir7
        self.SortDir8 = sort_dir8
        self.SortDir9 = sort_dir9
        self.SortField = sort_field
        self.SortField1 = sort_field1
        self.SortField10 = sort_field10
        self.SortField2 = sort_field2
        self.SortField3 = sort_field3
        self.SortField4 = sort_field4
        self.SortField5 = sort_field5
        self.SortField6 = sort_field6
        self.SortField7 = sort_field7
        self.SortField8 = sort_field8
        self.SortField9 = sort_field9
        self.SortFields = sort_fields
        self.SortFieldValues = sort_field_values
        self.View = view
        self.ViewCount = view_count
        self.ViewId = view_id
        self.ViewPath = view_path
        self.WebPartId = web_part_id

    @property
    def entity_type_name(self):
        return "SP.RenderListDataOverrideParameters"
