from enum import Enum


class ResponseEmotionType(Enum):
    none = "0"
    confident = "1"
    excited = "2"
    happy = "3"
    motivated = "4"
    peaceful = "5"
    ambitious = "6"
    cheerful = "7"
    comfortable = "8"
    creative = "9"
    determined = "10"
    energized = "11"
    focused = "12"
    fulfilled = "13"
    grateful = "14"
    included = "15"
    inspired = "16"
    optimistic = "17"
    proud = "18"
    successful = "19"
    valuable = "20"
    annoyed = "21"
    bored = "22"
    calm = "23"
    confused = "24"
    glad = "25"
    content = "26"
    pensive = "27"
    reserved = "28"
    restless = "29"
    shocked = "30"
    tired = "31"
    angry = "32"
    depressed = "33"
    exhausted = "34"
    lonely = "35"
    nervous = "36"
    anxious = "37"
    apathetic = "38"
    concerned = "39"
    disappointed = "40"
    frightened = "41"
    frustrated = "42"
    hopeless = "43"
    hurt = "44"
    jealous = "45"
    miserable = "46"
    overwhelmed = "47"
    skeptical = "48"
    stressed = "49"
    stuck = "50"
    worthless = "51"
    awed = "52"
    ashamed = "53"
    curious = "54"
    sensitive = "55"
    sad = "56"
    unknownFutureValue = "57"

    @property
    def entity_type_name(self):
        return "microsoft.graph.ResponseEmotionType"
